export interface SeoPageData {
  slug: string;
  type: "core" | "district" | "mahalle-block" | "mahalle" | "category" | "blog" | "keyword";
  title: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string;
  h1: string;
  intro: string[];
  features?: string[];
  mahalleler?: string[];
  faq: { q: string; a: string }[];
  internalLinks: { text: string; href: string }[];
  parentDistrict?: string;
}

export const SEO_PAGES: SeoPageData[] = [
  {
    slug: "samsun-petshop",
    type: "core",
    title: "Samsun Pet Shop",
    metaTitle: "Samsun Pet Shop - Kapıya Teslim Evcil Hayvan Ürünleri | JETGO",
    metaDescription: "Samsun'un en hızlı kapıya teslim pet shop'u. Kedi maması, köpek maması, kedi kumu ve tüm evcil hayvan ürünleri aynı gün teslimat. 900+ ürün, uygun fiyat.",
    keywords: "samsun petshop, samsun pet shop, samsun evcil hayvan, kapıya teslim petshop samsun, samsun kedi maması, samsun köpek maması",
    h1: "Samsun Kapıya Teslim Pet Shop",
    intro: [
      "JETGO, Samsun'un en kapsamlı kapıya teslim pet shop hizmetidir. 900'den fazla ürün çeşidiyle kedi, köpek, kuş ve kemirgen sahiplerine hızlı ve güvenilir teslimat sunuyoruz. Samsun'un Atakum, İlkadım, Canik ve Tekkeköy ilçelerine aynı gün teslimat yapıyoruz.",
      "Royal Canin, Hill's Science Plan, N&D, Pro Plan, Reflex ve daha birçok premium markayı uygun fiyatlarla kapınıza getiriyoruz. Nakit ödemede ekstra avantajlı fiyatlarımızdan yararlanın.",
      "Sipariş vermek çok kolay: ürünlerinizi seçin, sepete ekleyin ve WhatsApp üzerinden siparişinizi tamamlayın. Aynı gün içinde teslimat ekibimiz siparişinizi kapınıza getirir.",
    ],
    features: [
      "900+ ürün çeşidi",
      "Aynı gün teslimat",
      "Nakit ödemede avantajlı fiyat",
      "WhatsApp ile kolay sipariş",
      "Atakum, İlkadım, Canik, Tekkeköy teslimat",
      "Para Puan ile kazanç",
      "Ücretsiz kargo seçeneği",
      "Kapıda POS ödeme",
    ],
    mahalleler: [
      "Atakum", "İlkadım", "Canik", "Tekkeköy",
      "Yeni Mahalle", "Denizevleri", "Güzelyalı", "Kurupelit",
      "Atakent", "İncesu", "Körfez", "Mimar Sinan",
      "Kadıköy", "Rasathane", "Kılıçdede", "Baruthane",
    ],
    faq: [
      { q: "Samsun'da pet shop teslimat süresi ne kadar?", a: "Samsun merkez ilçelere (Atakum, İlkadım, Canik) aynı gün teslimat yapıyoruz. Siparişinizi sabah verirseniz akşama kadar elinizde olur." },
      { q: "Minimum sipariş tutarı nedir?", a: "Minimum sipariş tutarımız 700 TL'dir. 2.000 TL ve üzeri siparişlerde kargo ücretsizdir." },
      { q: "Hangi ödeme yöntemlerini kabul ediyorsunuz?", a: "Kapıda nakit, kapıda kredi kartı, banka havalesi ve QR ödeme seçeneklerimiz mevcuttur." },
      { q: "Hangi markaları satıyorsunuz?", a: "Royal Canin, Hill's, N&D, Pro Plan, Reflex, Profine, Gimcat ve daha birçok premium markayı satıyoruz." },
      { q: "Samsun'da hangi bölgelere teslimat yapıyorsunuz?", a: "Atakum, İlkadım, Canik ve Tekkeköy ilçelerinin tüm mahallelerine teslimat yapıyoruz." },
    ],
    internalLinks: [
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
      { text: "Atakum Pet Shop", href: "/atakum-petshop" },
      { text: "İlkadım Pet Shop", href: "/ilkadim-petshop" },
    ],
  },
  {
    slug: "atakum-petshop",
    type: "district",
    title: "Atakum Pet Shop",
    metaTitle: "Atakum Pet Shop - Aynı Gün Kapıya Teslim | JETGO Samsun",
    metaDescription: "Atakum'a aynı gün teslimat yapan pet shop. Kedi maması, köpek maması, kedi kumu ve evcil hayvan ürünleri. Denizevleri, Güzelyalı, Kurupelit, Atakent teslimat.",
    keywords: "atakum petshop, atakum pet shop, atakum kedi maması, atakum köpek maması, atakum kapıya teslim",
    h1: "Atakum Kapıya Teslim Pet Shop",
    intro: [
      "Atakum'un en güvenilir kapıya teslim pet shop hizmeti JETGO ile tanışın. Denizevleri'nden Güzelyalı'ya, Kurupelit'ten Atakent'e kadar Atakum'un her mahallesine aynı gün teslimat yapıyoruz.",
      "Kedi maması, köpek maması, kedi kumu, kuş yemi, kemirgen ürünleri ve tüm evcil hayvan aksesuarlarını kapınıza getiriyoruz. Royal Canin, Hill's, N&D gibi premium markaları en uygun fiyatlarla sunuyoruz.",
      "Atakum sahil şeridindeki müşterilerimize özel hızlı teslimat avantajımızdan yararlanın. Sabah siparişleriniz öğleden sonra kapınızda.",
    ],
    mahalleler: [
      "Yeni Mahalle", "Denizevleri", "Güzelyalı", "Kurupelit",
      "Atakent", "İncesu", "Balaç", "Çakırlar",
      "Mimar Sinan", "Körfez", "Soğuksu", "Taflan",
      "Altınkum", "Çobanlı", "Büyükoyumca",
    ],
    faq: [
      { q: "Atakum'a teslimat süresi ne kadar?", a: "Atakum ilçesine ortalama 1-3 saat içinde teslimat yapıyoruz. Sahil şeridine daha da hızlı ulaşıyoruz." },
      { q: "Denizevleri'ne teslimat yapıyor musunuz?", a: "Evet, Denizevleri mahallesine düzenli teslimat yapıyoruz. Aynı gün teslimat garantisi sunuyoruz." },
      { q: "Atakum'da minimum sipariş tutarı nedir?", a: "Atakum için minimum sipariş tutarımız 700 TL'dir. Mahalle bazlı farklı kargo ücretleri uygulanabilir." },
      { q: "Güzelyalı'ya teslimat var mı?", a: "Evet, Güzelyalı dahil Atakum'un tüm mahallelerine teslimat yapıyoruz." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Atakum Mahalleler", href: "/atakum-mahalleler" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
    ],
  },
  {
    slug: "ilkadim-petshop",
    type: "district",
    title: "İlkadım Pet Shop",
    metaTitle: "İlkadım Pet Shop - Aynı Gün Kapıya Teslim | JETGO Samsun",
    metaDescription: "İlkadım'a aynı gün teslimat yapan pet shop. Kadıköy, Rasathane, Kılıçdede, Baruthane mahallelerine hızlı teslimat. Kedi köpek maması, kedi kumu.",
    keywords: "ilkadım petshop, ilkadım pet shop, ilkadım kedi maması, ilkadım köpek maması, ilkadım kapıya teslim",
    h1: "İlkadım Kapıya Teslim Pet Shop",
    intro: [
      "İlkadım ilçesine aynı gün kapıya teslim pet shop hizmeti. Kadıköy, Rasathane, Kılıçdede, Kalkancı, Baruthane ve Ulugazi mahallelerine hızlı teslimat yapıyoruz.",
      "Samsun'un merkezi İlkadım ilçesinde yaşayan evcil hayvan sahipleri için 900'den fazla ürün seçeneği sunuyoruz. Premium kedi maması, köpek maması, kedi kumu ve aksesuar ürünlerini uygun fiyatlarla kapınıza getiriyoruz.",
      "İlkadım'ın yoğun trafiğinde mağaza mağaza dolaşmak yerine, JETGO ile tüm evcil hayvan ihtiyaçlarınızı tek tıkla sipariş edin. Aynı gün kapınıza getirelim.",
    ],
    mahalleler: [
      "Kadıköy", "Rasathane", "Kılıçdede",
      "Kalkancı", "Baruthane", "Ulugazi",
      "Derecik", "Adalet", "Çiftlik",
    ],
    faq: [
      { q: "İlkadım'a teslimat süresi ne kadar?", a: "İlkadım merkezine 1-2 saat içinde teslimat yapıyoruz." },
      { q: "Kadıköy mahallesine teslimat var mı?", a: "Evet, Kadıköy dahil İlkadım'ın tüm mahallelerine teslimat yapıyoruz." },
      { q: "İlkadım'da hangi markalar mevcut?", a: "Royal Canin, Hill's, N&D, Pro Plan, Reflex ve daha birçok marka mevcuttur." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
      { text: "Canik Pet Shop", href: "/canik-petshop" },
    ],
  },
  {
    slug: "canik-petshop",
    type: "district",
    title: "Canik Pet Shop",
    metaTitle: "Canik Pet Shop - Aynı Gün Kapıya Teslim | JETGO Samsun",
    metaDescription: "Canik'e aynı gün teslimat yapan pet shop. Karşıyaka, Gaziosmanpaşa, Yenimahalle mahallelerine hızlı teslimat. Kedi köpek maması, kedi kumu.",
    keywords: "canik petshop, canik pet shop, canik kedi maması, canik köpek maması, canik kapıya teslim",
    h1: "Canik Kapıya Teslim Pet Shop",
    intro: [
      "Canik ilçesine aynı gün kapıya teslim pet shop hizmeti. Karşıyaka, Gaziosmanpaşa, Yenimahalle ve Kuzeyyıldızı mahallelerine düzenli teslimat yapıyoruz.",
      "Canik'te yaşayan evcil hayvan sahipleri için premium marka kedi maması, köpek maması, kedi kumu ve aksesuar ürünlerini uygun fiyatlarla sunuyoruz. JETGO ile sipariş verin, aynı gün kapınıza getirelim.",
      "Canik bölgesindeki müşterilerimize özel kampanya ve indirimlerden haberdar olmak için üye olun. Para Puan sistemiyle her siparişte kazanın.",
    ],
    mahalleler: [
      "Karşıyaka", "Gaziosmanpaşa", "Yenimahalle", "Kuzeyyıldızı",
    ],
    faq: [
      { q: "Canik'e teslimat süresi ne kadar?", a: "Canik ilçesine ortalama 1-3 saat içinde teslimat yapıyoruz." },
      { q: "Canik'te minimum sipariş tutarı nedir?", a: "Minimum sipariş tutarımız 700 TL'dir." },
      { q: "Canik Karşıyaka'ya teslimat var mı?", a: "Evet, Karşıyaka dahil Canik'in tüm mahallelerine teslimat yapıyoruz." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "İlkadım Pet Shop", href: "/ilkadim-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
    ],
  },
  {
    slug: "atakum-mahalleler",
    type: "mahalle-block",
    title: "Atakum Mahalleler",
    metaTitle: "Atakum Mahallelerine Pet Shop Teslimat | JETGO Samsun",
    metaDescription: "Atakum'un tüm mahallelerine aynı gün pet shop teslimatı. Denizevleri, Güzelyalı, Kurupelit, Atakent, İncesu, Mimar Sinan ve diğer mahalleler.",
    keywords: "atakum mahalleler petshop, denizevleri petshop, güzelyalı petshop, kurupelit petshop, atakent petshop",
    h1: "Atakum Tüm Mahalleler - Pet Shop Teslimat",
    intro: [
      "JETGO olarak Atakum ilçesinin tüm mahallelerine evcil hayvan ürünleri teslimatı yapıyoruz. Sahil şeridinden iç mahallelere kadar her noktaya aynı gün ulaşıyoruz.",
      "Aşağıda Atakum'un teslimat yaptığımız tüm mahallelerini ve teslimat detaylarını bulabilirsiniz.",
    ],
    mahalleler: [
      "Yeni Mahalle", "Denizevleri", "Güzelyalı", "Kurupelit",
      "Atakent", "İncesu", "Balaç", "Çakırlar",
      "Mimar Sinan", "Körfez", "Soğuksu", "Taflan",
      "Altınkum", "Çobanlı", "Büyükoyumca", "Kozalak",
      "Kamalı", "Çamlık", "Yeşildere", "Yeşilyurt",
    ],
    faq: [
      { q: "Atakum'un en uzak mahallesine teslimat yapıyor musunuz?", a: "Evet, Taflan ve Balaç dahil Atakum'un tüm mahallelerine teslimat yapıyoruz." },
      { q: "Sahil şeridine teslimat süresi ne kadar?", a: "Denizevleri, Güzelyalı ve Altınkum gibi sahil mahallelerine 1-2 saat içinde teslimat yapıyoruz." },
    ],
    internalLinks: [
      { text: "Atakum Pet Shop", href: "/atakum-petshop" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
    ],
  },
  {
    slug: "kedi-mamasi",
    type: "category",
    title: "Kedi Maması",
    metaTitle: "Kedi Maması - En İyi Markalar, Uygun Fiyat | JETGO Samsun Pet Shop",
    metaDescription: "Samsun'da kedi maması kapıya teslim. Royal Canin, Hill's, N&D, Pro Plan, Reflex kedi maması. Yavru, yetişkin, kısırlaştırılmış kedi mamaları. Aynı gün teslimat.",
    keywords: "kedi maması, kedi maması samsun, en iyi kedi maması, ucuz kedi maması, royal canin kedi, hills kedi maması",
    h1: "Kedi Maması - Samsun Kapıya Teslim",
    intro: [
      "JETGO'da kedi maması çeşitlerimizle kedinizin beslenme ihtiyaçlarını en iyi şekilde karşılayın. Royal Canin, Hill's Science Plan, N&D, Pro Plan ve Reflex gibi dünya markalarını uygun fiyatlarla kapınıza getiriyoruz.",
      "Yavru kedi maması, yetişkin kedi maması, kısırlaştırılmış kedi maması, hassas sindirimli kedi maması ve özel diyet kedi mamalarını geniş ürün yelpazemizde bulabilirsiniz.",
      "Kuru mama, yaş mama ve ödül maması seçenekleriyle kedinizin damak zevkine uygun ürünü kolayca bulun. Büyük boy paketlerde ekstra tasarruf fırsatı yakalayın.",
    ],
    features: [
      "Royal Canin - FIT 32, Indoor, Sensible, Sterilised",
      "Hill's Science Plan - Yetişkin, Yavru, Kısırlaştırılmış",
      "N&D - Düşük Tahıllı, Tahılsız, Tropical Selection",
      "Pro Plan - Adult, Kitten, Sterilised",
      "Reflex / Reflex Plus - Ekonomik seçenekler",
      "Profine - Glutensiz premium mamalar",
      "Pronature - Doğal içerikli mamalar",
    ],
    faq: [
      { q: "En iyi kedi maması hangisi?", a: "Kedinizin yaşına, sağlık durumuna ve tercihine göre değişir. Premium markalar arasında Royal Canin, Hill's ve N&D en çok tercih edilen markalardır." },
      { q: "Kısırlaştırılmış kedi maması neden farklı?", a: "Kısır kedilerin metabolizması yavaşlar ve kilo alma eğilimleri artar. Kısır kedi mamaları düşük kalorili ve idrar yolu sağlığını destekleyecek şekilde formüle edilmiştir." },
      { q: "Kedi maması ne kadar?", a: "Fiyatlar markaya ve pakete göre değişir. 1,5 kg paketler 200-900 TL, 10-15 kg paketler 2.000-6.000 TL arasındadır." },
      { q: "Samsun'da kedi maması aynı gün gelir mi?", a: "Evet, saat 17:00'ye kadar verilen siparişler aynı gün teslim edilir." },
    ],
    internalLinks: [
      { text: "En İyi Kedi Maması Markaları", href: "/kedi-mamasi-en-iyi-markalar" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kategorisi", href: "/kategori/kedi" },
    ],
  },
  {
    slug: "kopek-mamasi",
    type: "category",
    title: "Köpek Maması",
    metaTitle: "Köpek Maması - En İyi Markalar, Uygun Fiyat | JETGO Samsun Pet Shop",
    metaDescription: "Samsun'da köpek maması kapıya teslim. Royal Canin, Hill's, N&D, Pro Plan köpek maması. Yavru, yetişkin, büyük/küçük ırk. Aynı gün teslimat.",
    keywords: "köpek maması, köpek maması samsun, en iyi köpek maması, ucuz köpek maması, royal canin köpek, hills köpek maması",
    h1: "Köpek Maması - Samsun Kapıya Teslim",
    intro: [
      "JETGO'da köpek maması çeşitlerimizle köpeğinizin beslenme ihtiyaçlarını karşılayın. Küçük ırk, orta ırk ve büyük ırk köpekler için özel formüle edilmiş mamaları uygun fiyatlarla sunuyoruz.",
      "Royal Canin, Hill's Science Plan, N&D, Pro Plan, Reflex ve Pro Performance gibi güvenilir markaları kapınıza getiriyoruz. Yavru köpek mamasından yetişkin köpek mamasına, hassas sindirimden kilo kontrolüne kadar her ihtiyaca uygun seçenek mevcut.",
      "15 kg'lık büyük paketlerde ekonomik fiyatlar ve nakit ödemede ekstra avantaj sunuyoruz. Köpeğinizin sağlıklı beslenmesi için doğru mamayı seçmenize yardımcı oluyoruz.",
    ],
    features: [
      "Royal Canin - Maxi, Mini, Medium (Yavru & Yetişkin)",
      "Hill's Science Plan - Sensitive, Hypoallergenic, Light",
      "N&D - Düşük Tahıllı, Tahılsız, Quinoa, Pumpkin",
      "Pro Plan - Adult, Puppy, Sensitive Skin",
      "Reflex / Reflex Plus - Ekonomik büyük paketler",
      "Pro Performance - Premium ekonomik seçenek",
      "Profine - Glutensiz, Hipoalerjenik",
    ],
    faq: [
      { q: "Büyük ırk köpek maması hangisi?", a: "Royal Canin Maxi, Hill's Large Breed ve N&D büyük ırk köpekler için özel formüle edilmiş mamalardır." },
      { q: "Yavru köpek maması ne zaman değiştirilmeli?", a: "Küçük ırk köpekler 10 aylıkken, büyük ırk köpekler 15-18 aylıkken yetişkin mamasına geçiş yapılmalıdır." },
      { q: "Köpek maması fiyatları ne kadar?", a: "12-15 kg paketler markaya göre 1.800-7.000 TL arasında değişmektedir. Nakit ödemede ek indirim uygulanır." },
      { q: "Samsun'da köpek maması teslimat yapıyor musunuz?", a: "Evet, Samsun merkez ilçelerine aynı gün köpek maması teslimatı yapıyoruz." },
    ],
    internalLinks: [
      { text: "Köpek Maması Fiyatları", href: "/kopek-mamasi-fiyatlari" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Pet Aksesuar", href: "/pet-aksesuar" },
      { text: "Köpek Kategorisi", href: "/kategori/kopek" },
    ],
  },
  {
    slug: "kedi-kumu",
    type: "category",
    title: "Kedi Kumu",
    metaTitle: "Kedi Kumu - En İyi Markalar, Kapıya Teslim | JETGO Samsun Pet Shop",
    metaDescription: "Samsun'da kedi kumu kapıya teslim. Bentonit, silika, doğal kedi kumu. Van Cat, Biokat's, Sanicat. Topaklanan, aktif karbonlu, aromalı kedi kumları.",
    keywords: "kedi kumu, kedi kumu samsun, en iyi kedi kumu, ucuz kedi kumu, bentonit kedi kumu, topaklanan kedi kumu",
    h1: "Kedi Kumu - Samsun Kapıya Teslim",
    intro: [
      "Ağır kedi kumunu taşımaktan kurtulun! JETGO ile kedi kumunuzu kapınıza getiriyoruz. Bentonit, silika ve doğal kedi kumu çeşitlerimizle kedinizin konforunu sağlayın.",
      "Van Cat, Biokat's, Sanicat ve daha birçok markanın aktif karbonlu, aromalı ve ince taneli kedi kumlarını uygun fiyatlarla sunuyoruz. Topaklanan kedi kumları ile kolay temizlik, koku kontrolü ve uzun ömürlü kullanım.",
      "Kedi kumu taşımak zor ve zahmetli bir iş. JETGO'nun kapıya teslim hizmetiyle bu dertten kurtulun. Sipariş verin, biz kapınıza getirelim.",
    ],
    features: [
      "Van Cat - Aktif Karbonlu, İnce Taneli Bentonit",
      "Biokat's - Bianco Fresh, Aromalı Premium Kumlar",
      "Sanicat - Duo Vanilya, Mandalina Aromalı",
      "Topaklanan Bentonit Kumlar",
      "Aktif Karbonlu Koku Önleyici",
      "İnce ve Kalın Taneli Seçenekler",
    ],
    faq: [
      { q: "En iyi kedi kumu hangisi?", a: "Topaklanan bentonit kumlar en çok tercih edilen türdür. Aktif karbonlu seçenekler koku kontrolünde çok başarılıdır." },
      { q: "Kedi kumu ne sıklıkla değiştirilmeli?", a: "Topaklanan kumlar günlük temizlenip 2-3 haftada bir tamamen değiştirilmelidir." },
      { q: "Kedi kumu kapıya teslim var mı?", a: "Evet, Samsun merkez ilçelerine aynı gün kedi kumu teslimatı yapıyoruz. Ağır kumları taşıma derdi yok." },
      { q: "Kedi kumu fiyatları ne kadar?", a: "10 litrelik kedi kumları 100-600 TL arasında değişmektedir." },
    ],
    internalLinks: [
      { text: "En İyi Kedi Kumu Karşılaştırma", href: "/kedi-kumu-en-iyi" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Kategorisi", href: "/kategori/kedi" },
    ],
  },
  {
    slug: "pet-aksesuar",
    type: "category",
    title: "Pet Aksesuar",
    metaTitle: "Pet Aksesuar - Kedi Köpek Aksesuarları | JETGO Samsun Pet Shop",
    metaDescription: "Kedi ve köpek aksesuarları kapıya teslim. Taşıma çantası, mama kabı, oyuncak, tasma, yataklar. Samsun'da aynı gün teslimat.",
    keywords: "pet aksesuar, kedi aksesuar, köpek aksesuar, evcil hayvan aksesuar, pet shop aksesuar samsun",
    h1: "Pet Aksesuar - Kedi & Köpek Aksesuarları",
    intro: [
      "Evcil hayvanınız için ihtiyacınız olan tüm aksesuarları JETGO'da bulun. Taşıma çantaları, mama ve su kapları, oyuncaklar, tasmalar, yataklar ve bakım ürünleri kapınıza gelsin.",
      "Köpek arabası, kedi tırmalama tahtası, çiş eğitim pedi, diş bakım ürünleri ve daha fazlasını uygun fiyatlarla sunuyoruz. Tommy, Pawise, M-Pets, Ferplast gibi kaliteli markalar mevcut.",
      "Evcil hayvanınızın konforunu ve mutluluğunu artıracak ürünleri keşfedin. Samsun'a aynı gün teslimat ile hemen sipariş verin.",
    ],
    features: [
      "Taşıma Çantaları ve Kafesleri",
      "Köpek Arabaları (Tommy, Pawise)",
      "Mama ve Su Kapları",
      "Çiş Eğitim Pedleri",
      "Diş Bakım Ürünleri",
      "Tırnak Makasları ve Bakım Setleri",
      "Şampuan ve Bakım Ürünleri",
    ],
    faq: [
      { q: "Köpek arabası fiyatları ne kadar?", a: "Köpek arabaları modeline göre 2.500-7.000 TL arasında değişmektedir." },
      { q: "Kedi taşıma çantası var mı?", a: "Evet, Ferplast Atlas ve diğer markaların taşıma çantaları mevcuttur." },
      { q: "Aksesuar ürünleri kapıya teslim var mı?", a: "Evet, tüm aksesuar ürünlerimiz Samsun merkez ilçelerine aynı gün teslim edilir." },
    ],
    internalLinks: [
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Köpek Kategorisi", href: "/kategori/kopek" },
    ],
  },
  {
    slug: "kedi-mamasi-en-iyi-markalar",
    type: "blog",
    title: "En İyi Kedi Maması Markaları 2026",
    metaTitle: "En İyi Kedi Maması Markaları 2026 - Karşılaştırma ve Öneriler | JETGO",
    metaDescription: "2026'da en iyi kedi maması markaları karşılaştırması. Royal Canin, Hill's, N&D, Pro Plan hangisi daha iyi? Uzman önerileri ve fiyat karşılaştırması.",
    keywords: "en iyi kedi maması, kedi maması karşılaştırma, royal canin mi hills mi, kedi maması önerisi 2026",
    h1: "En İyi Kedi Maması Markaları 2026 - Karşılaştırma Rehberi",
    intro: [
      "Kediniz için en iyi mamayı seçmek önemli bir karar. Bu rehberde 2026 yılında Türkiye'de satılan en iyi kedi maması markalarını karşılaştırıyoruz. Her markanın avantajları, dezavantajları ve fiyat aralıklarını detaylı şekilde inceliyoruz.",
      "Veteriner hekimlerin önerdiği premium markalardan ekonomik alternatiflere kadar, kedinizin yaşına ve sağlık durumuna uygun mamayı bu rehberle kolayca bulabilirsiniz.",
      "Royal Canin, Hill's Science Plan, N&D Farmina, Pro Plan ve Reflex Plus markalarını protein oranı, içerik kalitesi ve fiyat-performans açısından değerlendirdik.",
    ],
    features: [
      "Royal Canin - Veteriner onaylı, geniş ürün yelpazesi, yaş ve ırka özel formüller. Sensible 33 hassas sindirim için ideal.",
      "Hill's Science Plan - Bilimsel araştırmaya dayalı, hassas mide ve cilt sağlığı için özel formüller. Hypoallergenic böcek proteinli seçenek benzersiz.",
      "N&D Farmina - Düşük tahıllı ve tahılsız premium mamalar. Doğal içerikler, yüksek et oranı. Kısırlaştırılmış kedi seçenekleri güçlü.",
      "Pro Plan - Purina'nın premium markası. Uygun fiyatlı premium alternatif. Yavru ve yetişkin seçenekleri zengin.",
      "Reflex Plus - Türkiye üretimi, ekonomik premium. Büyük paketlerde tasarruf. Orta segment için ideal seçim.",
    ],
    faq: [
      { q: "Royal Canin mi Hill's mi?", a: "Her iki marka da veteriner onaylı premium markalardır. Royal Canin ırka özel formüllerde, Hill's ise hassas sağlık durumlarında öne çıkar." },
      { q: "N&D kedi maması iyi mi?", a: "Evet, N&D İtalyan üretimi premium bir markadır. Düşük tahıllı ve tahılsız seçenekleriyle yüksek et oranı sunar." },
      { q: "En ucuz premium kedi maması hangisi?", a: "Reflex Plus ve Pro Performance, premium segmentte en uygun fiyatlı seçeneklerdir." },
      { q: "Kedi maması nereden alınır?", a: "JETGO Pet Shop'tan online sipariş vererek Samsun'da aynı gün teslim alabilirsiniz." },
    ],
    internalLinks: [
      { text: "Kedi Maması Ürünleri", href: "/kedi-mamasi" },
      { text: "Kedi Kumu Karşılaştırma", href: "/kedi-kumu-en-iyi" },
      { text: "Kedi Kategorisi", href: "/kategori/kedi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
    ],
  },
  {
    slug: "kedi-kumu-en-iyi",
    type: "blog",
    title: "En İyi Kedi Kumu Karşılaştırma 2026",
    metaTitle: "En İyi Kedi Kumu 2026 - Bentonit, Silika Karşılaştırma | JETGO",
    metaDescription: "2026'da en iyi kedi kumu karşılaştırması. Bentonit mi silika mı? Van Cat, Biokat's, Sanicat hangisi daha iyi? Topaklanan kedi kumu önerileri.",
    keywords: "en iyi kedi kumu, kedi kumu karşılaştırma, bentonit kedi kumu, topaklanan kedi kumu, kedi kumu önerisi",
    h1: "En İyi Kedi Kumu 2026 - Karşılaştırma Rehberi",
    intro: [
      "Doğru kedi kumunu seçmek hem kedinizin hem sizin konforunuz için kritik. Bu rehberde bentonit, silika ve doğal kedi kumlarını karşılaştırıyoruz.",
      "Topaklanan kedi kumları temizlik kolaylığı ve koku kontrolü açısından en popüler seçenektir. Aktif karbonlu kumlar koku emiliminde extra başarılıdır.",
      "Van Cat, Biokat's ve Sanicat gibi lider markaların ürünlerini detaylı olarak inceliyoruz. Her markanın güçlü ve zayıf yönlerini, fiyat karşılaştırmasını sunuyoruz.",
    ],
    features: [
      "Van Cat - Aktif karbonlu, ince taneli bentonit. Türkiye'nin en çok satılan kedi kumu. Güçlü topaklanma, ekonomik fiyat.",
      "Biokat's - Almanya üretimi premium bentonit. Bianco Fresh mandalina aromalı seçenek çok popüler. Üstün koku kontrolü.",
      "Sanicat - İspanya üretimi kaliteli kumlar. Duo serisi vanilya ve mandalina aromalı. İyi topaklanma performansı.",
    ],
    faq: [
      { q: "Bentonit mi silika kedi kumu mu?", a: "Bentonit kumlar daha ekonomik ve topaklanan yapısıyla temizlemesi kolaydır. Silika kumlar daha uzun ömürlü ama pahalıdır. Çoğu kedi sahibi bentonit tercih eder." },
      { q: "Aktif karbonlu kedi kumu ne işe yarar?", a: "Aktif karbon kötü kokuları emer ve nötralize eder. Özellikle apartman dairelerinde yaşayan kedi sahipleri için idealdir." },
      { q: "Kedi kumu ne sıklıkla değiştirilir?", a: "Topaklanan bentonit kumlar günlük pislik temizliği yapılarak 2-3 haftada bir tamamen değiştirilmelidir." },
    ],
    internalLinks: [
      { text: "Kedi Kumu Ürünleri", href: "/kedi-kumu" },
      { text: "Kedi Maması Markaları", href: "/kedi-mamasi-en-iyi-markalar" },
      { text: "Kedi Kategorisi", href: "/kategori/kedi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
    ],
  },
  {
    slug: "kopek-mamasi-fiyatlari",
    type: "blog",
    title: "Köpek Maması Fiyatları 2026",
    metaTitle: "Köpek Maması Fiyatları 2026 - Marka Karşılaştırma | JETGO Samsun",
    metaDescription: "2026 güncel köpek maması fiyatları. Royal Canin, Hill's, N&D, Pro Plan, Reflex köpek maması fiyat karşılaştırması. En uygun fiyat garantisi.",
    keywords: "köpek maması fiyatları, köpek maması fiyat, ucuz köpek maması, köpek maması fiyat karşılaştırma 2026",
    h1: "Köpek Maması Fiyatları 2026 - Güncel Fiyat Rehberi",
    intro: [
      "2026 yılında köpek maması fiyatları markaya, paket boyutuna ve içeriğe göre büyük farklılıklar göstermektedir. Bu rehberde en popüler köpek maması markalarının güncel fiyatlarını karşılaştırıyoruz.",
      "Premium markalardan ekonomik alternatiflere kadar, bütçenize ve köpeğinizin ihtiyaçlarına uygun mamayı bulmak için bu fiyat rehberini kullanabilirsiniz.",
      "JETGO'da nakit ödemede ekstra avantajlı fiyatlar ve belirli tutar üzeri ücretsiz kargo sunuyoruz. Samsun'da en uygun köpek maması fiyatları için JETGO'yu tercih edin.",
    ],
    features: [
      "Royal Canin 15 kg: 4.200 - 4.700 TL arası (ırka göre değişir)",
      "Hill's Science Plan 14 kg: 3.500 - 5.500 TL arası",
      "N&D 12 kg: 4.200 - 6.900 TL arası (tahılsız daha pahalı)",
      "Pro Plan 14 kg: 3.500 - 5.300 TL arası",
      "Reflex 15 kg: 1.850 - 2.450 TL arası (en ekonomik premium)",
      "Pro Performance 18 kg: 2.500 - 2.600 TL arası (kg başı en uygun)",
      "Profine 12 kg: 3.000 - 3.500 TL arası (glutensiz premium)",
    ],
    faq: [
      { q: "En ucuz köpek maması hangisi?", a: "Premium segmentte Reflex ve Pro Performance en uygun fiyatlı markalardır. 15-18 kg paketlerde kg başı 120-150 TL civarındadır." },
      { q: "Royal Canin köpek maması fiyatı ne kadar?", a: "Royal Canin 15 kg paketler 4.200-4.700 TL arasındadır. Irka ve yaşa göre fiyat değişir." },
      { q: "Köpek maması ödeme yöntemleri neler?", a: "Kapıda nakit (%5 indirim), kapıda POS ile kredi kartı, QR ödeme ve banka havalesi seçenekleri mevcuttur." },
      { q: "Samsun'da en ucuz köpek maması nerede?", a: "JETGO Pet Shop, Samsun'da nakit ödemede en uygun fiyatları sunan kapıya teslim pet shop'tur." },
    ],
    internalLinks: [
      { text: "Köpek Maması Ürünleri", href: "/kopek-mamasi" },
      { text: "Kedi Maması Markaları", href: "/kedi-mamasi-en-iyi-markalar" },
      { text: "Köpek Kategorisi", href: "/kategori/kopek" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Pet Aksesuar", href: "/pet-aksesuar" },
    ],
  },
];

interface MahalleConfig {
  name: string;
  slug: string;
  district: string;
  districtSlug: string;
  nearby: string[];
  landmark?: string;
}

const ATAKUM_MAHALLELER: MahalleConfig[] = [
  { name: "Denizevleri", slug: "denizevleri", district: "Atakum", districtSlug: "atakum", nearby: ["Güzelyalı", "Altınkum", "Yeni Mahalle"], landmark: "sahil şeridi" },
  { name: "Güzelyalı", slug: "guzelyali", district: "Atakum", districtSlug: "atakum", nearby: ["Denizevleri", "Kurupelit", "Atakent"], landmark: "Güzelyalı sahil" },
  { name: "Kurupelit", slug: "kurupelit", district: "Atakum", districtSlug: "atakum", nearby: ["Güzelyalı", "Atakent", "OMÜ"], landmark: "Ondokuz Mayıs Üniversitesi" },
  { name: "Atakent", slug: "atakent", district: "Atakum", districtSlug: "atakum", nearby: ["Kurupelit", "İncesu", "Güzelyalı"], landmark: "Atakent konutları" },
  { name: "İncesu", slug: "incesu", district: "Atakum", districtSlug: "atakum", nearby: ["Atakent", "Körfez", "Mimar Sinan"] },
  { name: "Mimar Sinan", slug: "mimar-sinan", district: "Atakum", districtSlug: "atakum", nearby: ["İncesu", "Körfez", "Çakırlar"] },
  { name: "Körfez", slug: "korfez", district: "Atakum", districtSlug: "atakum", nearby: ["Mimar Sinan", "İncesu", "Soğuksu"] },
  { name: "Yeni Mahalle", slug: "yeni-mahalle", district: "Atakum", districtSlug: "atakum", nearby: ["Denizevleri", "Altınkum", "Balaç"], landmark: "Atatürk Bulvarı" },
  { name: "Altınkum", slug: "altinkum", district: "Atakum", districtSlug: "atakum", nearby: ["Yeni Mahalle", "Denizevleri", "Çobanlı"], landmark: "Altınkum plajı" },
  { name: "Balaç", slug: "balac", district: "Atakum", districtSlug: "atakum", nearby: ["Yeni Mahalle", "Çakırlar", "Taflan"] },
  { name: "Çakırlar", slug: "cakirlar", district: "Atakum", districtSlug: "atakum", nearby: ["Balaç", "Mimar Sinan", "Taflan"] },
  { name: "Soğuksu", slug: "soguksu", district: "Atakum", districtSlug: "atakum", nearby: ["Körfez", "Taflan", "Çakırlar"] },
  { name: "Taflan", slug: "taflan", district: "Atakum", districtSlug: "atakum", nearby: ["Soğuksu", "Balaç", "Çakırlar"] },
  { name: "Çobanlı", slug: "cobanli", district: "Atakum", districtSlug: "atakum", nearby: ["Altınkum", "Büyükoyumca", "Yeni Mahalle"] },
  { name: "Büyükoyumca", slug: "buyukoyumca", district: "Atakum", districtSlug: "atakum", nearby: ["Çobanlı", "Altınkum", "Kozalak"] },
];

const ILKADIM_MAHALLELER: MahalleConfig[] = [
  { name: "Kadıköy", slug: "kadikoy", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Rasathane", "Kılıçdede", "Adalet"], landmark: "İlkadım merkez" },
  { name: "Rasathane", slug: "rasathane", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Kadıköy", "Kılıçdede", "Baruthane"] },
  { name: "Kılıçdede", slug: "kilicdede", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Kadıköy", "Rasathane", "Kalkancı"] },
  { name: "Baruthane", slug: "baruthane", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Rasathane", "Ulugazi", "Derecik"] },
  { name: "Kalkancı", slug: "kalkanci", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Kılıçdede", "Adalet", "Çiftlik"] },
  { name: "Ulugazi", slug: "ulugazi", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Baruthane", "Derecik", "Rasathane"] },
  { name: "Derecik", slug: "derecik", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Baruthane", "Ulugazi", "Çiftlik"] },
  { name: "Adalet", slug: "adalet", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Kadıköy", "Kalkancı", "Çiftlik"], landmark: "Adalet Sarayı" },
  { name: "Çiftlik", slug: "ciftlik", district: "İlkadım", districtSlug: "ilkadim", nearby: ["Adalet", "Derecik", "Kalkancı"] },
];

const CANIK_MAHALLELER: MahalleConfig[] = [
  { name: "Karşıyaka", slug: "karsiyaka", district: "Canik", districtSlug: "canik", nearby: ["Gaziosmanpaşa", "Yenimahalle", "Kuzeyyıldızı"], landmark: "Karşıyaka merkez" },
  { name: "Gaziosmanpaşa", slug: "gaziosmanpasa", district: "Canik", districtSlug: "canik", nearby: ["Karşıyaka", "Yenimahalle", "Kuzeyyıldızı"] },
  { name: "Yenimahalle", slug: "canik-yenimahalle", district: "Canik", districtSlug: "canik", nearby: ["Karşıyaka", "Gaziosmanpaşa", "Kuzeyyıldızı"] },
  { name: "Kuzeyyıldızı", slug: "kuzeyyildizi", district: "Canik", districtSlug: "canik", nearby: ["Yenimahalle", "Gaziosmanpaşa", "Karşıyaka"] },
];

function generateMahallePage(m: MahalleConfig): SeoPageData {
  const nearbyText = m.nearby.join(", ");
  return {
    slug: `${m.districtSlug}-${m.slug}-petshop`,
    type: "mahalle",
    parentDistrict: m.districtSlug,
    title: `${m.name} Pet Shop`,
    metaTitle: `${m.name} Pet Shop - ${m.district} Kapıya Teslim | JETGO Samsun`,
    metaDescription: `${m.name} mahallesine aynı gün pet shop teslimatı. Kedi maması, köpek maması, kedi kumu kapıya teslim. ${nearbyText} yakını. JETGO Samsun.`,
    keywords: `${m.name.toLowerCase()} petshop, ${m.name.toLowerCase()} pet shop, ${m.name.toLowerCase()} kedi maması, ${m.name.toLowerCase()} köpek maması, ${m.district.toLowerCase()} ${m.name.toLowerCase()} petshop, ${m.name.toLowerCase()} kapıya teslim petshop`,
    h1: `${m.name} Kapıya Teslim Pet Shop`,
    intro: [
      `${m.name} mahallesine aynı gün kapıya teslim pet shop hizmeti! JETGO olarak ${m.district}'un ${m.name} mahallesine kedi maması, köpek maması, kedi kumu ve tüm evcil hayvan ürünlerini hızlıca ulaştırıyoruz.${m.landmark ? ` ${m.landmark} çevresindeki tüm noktalara teslimat yapıyoruz.` : ""}`,
      `${m.name} ve çevresindeki ${nearbyText} mahallelerine düzenli teslimat rotamız bulunmaktadır. Royal Canin, Hill's, N&D, Pro Plan ve Reflex gibi premium markaları kapınıza getiriyoruz.`,
      `Ağır mama ve kum çuvallarını taşımak zorunda kalmayın. JETGO ile online sipariş verin, aynı gün ${m.name} adresinize teslim edelim. Nakit, POS ve QR kod ile kapıda ödeme yapabilirsiniz.`,
    ],
    features: [
      `${m.name}'ye aynı gün teslimat`,
      "900+ ürün çeşidi",
      "Kapıda nakit, POS ve QR ödeme",
      "Her siparişte %5 para puan",
      `${nearbyText} mahallelerine de teslimat`,
      "Ücretsiz kargo seçeneği",
      "WhatsApp ile kolay sipariş",
    ],
    faq: [
      { q: `${m.name}'ye teslimat süresi ne kadar?`, a: `${m.name} mahallesine ortalama 1-2 saat içinde teslimat yapıyoruz. ${m.district} merkezine yakınlığı sayesinde hızlı ulaşım sağlıyoruz.` },
      { q: `${m.name}'de minimum sipariş tutarı nedir?`, a: `${m.name} mahallesi için minimum sipariş tutarı mahalle bazlı belirlenmektedir. Detaylar için sipariş sayfamızı kontrol edin.` },
      { q: `${m.name} yakınında pet shop var mı?`, a: `JETGO, ${m.name} ve çevresindeki ${nearbyText} mahallelerine kapıya teslim pet shop hizmeti sunmaktadır. Mağazaya gitmenize gerek yok!` },
      { q: `${m.name}'ye hangi ürünleri getiriyorsunuz?`, a: `Kedi maması, köpek maması, kedi kumu, kuş yemi, kemirgen ürünleri ve tüm evcil hayvan aksesuarlarını ${m.name}'ye teslim ediyoruz.` },
    ],
    internalLinks: [
      { text: `${m.district} Pet Shop`, href: `/${m.districtSlug}-petshop` },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
    ],
  };
}

const MAHALLE_PAGES: SeoPageData[] = [
  ...ATAKUM_MAHALLELER.map(generateMahallePage),
  ...ILKADIM_MAHALLELER.map(generateMahallePage),
  ...CANIK_MAHALLELER.map(generateMahallePage),
];

const KEYWORD_PAGES: SeoPageData[] = [
  {
    slug: "en-yakin-petshop-samsun",
    type: "keyword",
    title: "En Yakın Pet Shop Samsun",
    metaTitle: "En Yakın Pet Shop Samsun - Kapınıza Geliyoruz | JETGO",
    metaDescription: "Samsun'da en yakın pet shop'u aramayın, biz kapınıza geliyoruz! JETGO ile kedi maması, köpek maması, kedi kumu aynı gün teslimat. Atakum, İlkadım, Canik.",
    keywords: "en yakın petshop, yakınımda petshop, samsun en yakın pet shop, pet shop yakınımda, samsun petshop teslimat",
    h1: "Samsun'da En Yakın Pet Shop - Kapınıza Geliyoruz",
    intro: [
      "En yakın pet shop'u arıyorsunuz ama trafikte vakit kaybetmek istemiyorsunuz? JETGO ile evcil hayvan ürünlerinizi online sipariş verin, aynı gün kapınıza teslim edelim. Samsun'un Atakum, İlkadım ve Canik ilçelerine hızlı teslimat yapıyoruz.",
      "Artık ağır mama çuvallarını ve kedi kumunu taşımak zorunda değilsiniz. JETGO'nun kapıya teslim hizmeti ile en yakın pet shop her zaman cebinizde. WhatsApp veya web sitemiz üzerinden dakikalar içinde sipariş verin.",
      "900'den fazla ürün çeşidi, premium markalar ve uygun fiyatlarla Samsun'un en kapsamlı online pet shop'u JETGO'da. Her siparişte %5 para puan kazanın, sonraki alışverişinizde kullanın.",
    ],
    features: [
      "Aynı gün kapıya teslimat",
      "Atakum, İlkadım, Canik tüm mahallelere",
      "900+ ürün çeşidi",
      "Kapıda nakit, POS, QR ödeme",
      "Her siparişte %5 para puan",
      "WhatsApp ile kolay sipariş",
      "Premium markalar uygun fiyatla",
    ],
    faq: [
      { q: "Samsun'da en yakın pet shop nerede?", a: "JETGO ile pet shop'a gitmenize gerek yok! Online sipariş verin, aynı gün kapınıza teslim edelim. Atakum, İlkadım ve Canik'e teslimat yapıyoruz." },
      { q: "En yakın pet shop'a nasıl sipariş verilir?", a: "jetgo.shop adresinden veya WhatsApp üzerinden sipariş verebilirsiniz. Ürünlerinizi seçin, adresinizi belirtin, aynı gün teslim edelim." },
      { q: "Pet shop teslimat ücreti ne kadar?", a: "Teslimat ücreti mahallenize göre değişmektedir. Belirli tutar üzeri siparişlerde ücretsiz kargo seçeneği mevcuttur." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Atakum Pet Shop", href: "/atakum-petshop" },
      { text: "İlkadım Pet Shop", href: "/ilkadim-petshop" },
      { text: "Canik Pet Shop", href: "/canik-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
    ],
  },
  {
    slug: "kapiya-teslim-petshop-samsun",
    type: "keyword",
    title: "Kapıya Teslim Pet Shop Samsun",
    metaTitle: "Kapıya Teslim Pet Shop Samsun - Aynı Gün Teslimat | JETGO",
    metaDescription: "Samsun'da kapıya teslim pet shop hizmeti. Kedi maması, köpek maması, kedi kumu aynı gün adresinize. Nakit, kredi kartı, QR ödeme. JETGO.",
    keywords: "kapıya teslim petshop, petshop teslimat samsun, eve teslim pet shop, kapıya teslim kedi maması, kapıya teslim köpek maması",
    h1: "Samsun Kapıya Teslim Pet Shop",
    intro: [
      "JETGO, Samsun'un ilk kapıya teslim pet shop hizmetidir. Getir modeli ile evcil hayvan ürünlerinizi online sipariş verin, aynı gün kapınıza getirelim. Ağır mama ve kum çuvallarını taşıma derdi artık yok!",
      "Atakum, İlkadım ve Canik ilçelerinin tüm mahallelerine düzenli teslimat rotalarımız bulunmaktadır. Sabah verdiğiniz siparişler akşama kapınızda. Acil ihtiyaçlarınız için hızlandırılmış teslimat da mevcuttur.",
      "Kapıda nakit, POS cihazı ile kredi kartı ve QR kod ile ödeme seçenekleri sunuyoruz. Ödeme kolaylığı ile pet shop alışverişinizi kolaylaştırıyoruz.",
    ],
    features: [
      "Aynı gün kapıya teslimat garantisi",
      "Nakit, POS, QR ödeme",
      "900+ ürün çeşidi",
      "Royal Canin, Hill's, N&D, Pro Plan",
      "Her siparişte %5 para puan",
      "Ücretsiz kargo seçeneği",
      "WhatsApp ile anlık sipariş",
    ],
    faq: [
      { q: "Kapıya teslim pet shop nasıl çalışır?", a: "jetgo.shop üzerinden ürünlerinizi sepete ekleyin, WhatsApp ile siparişinizi onaylayın. Aynı gün kurye ekibimiz siparişinizi kapınıza getirir." },
      { q: "Kapıda hangi ödeme yöntemleri var?", a: "Kapıda nakit, kredi kartı (POS) ve QR kod ile ödeme yapabilirsiniz." },
      { q: "Teslimat ne kadar sürer?", a: "Samsun merkez ilçelerine ortalama 1-3 saat içinde teslimat yapıyoruz. Yoğunluğa göre değişebilir." },
      { q: "Minimum sipariş tutarı var mı?", a: "Evet, minimum sipariş tutarı mahalle bazlı belirlenmektedir. Ortalama 700 TL'dir." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Atakum Pet Shop", href: "/atakum-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
    ],
  },
  {
    slug: "online-petshop-samsun",
    type: "keyword",
    title: "Online Pet Shop Samsun",
    metaTitle: "Online Pet Shop Samsun - 900+ Ürün Aynı Gün Teslimat | JETGO",
    metaDescription: "Samsun online pet shop. 900+ kedi köpek ürünü, premium markalar, uygun fiyat. Aynı gün teslimat, kapıda ödeme. JETGO ile online evcil hayvan alışverişi.",
    keywords: "online petshop samsun, online pet shop, samsun online evcil hayvan, internet petshop samsun, online mama sipariş samsun",
    h1: "Samsun Online Pet Shop - JETGO",
    intro: [
      "Samsun'un en kapsamlı online pet shop'u JETGO ile evcil hayvan alışverişinizi kolaylaştırın. 900'den fazla ürün, premium markalar ve uygun fiyatlarla tüm ihtiyaçlarınızı tek tıkla karşılayın.",
      "Kedi maması, köpek maması, kedi kumu, kuş yemi, kemirgen ürünleri ve evcil hayvan aksesuarlarını online sipariş verin. Atakum, İlkadım ve Canik'e aynı gün kapıya teslim ediyoruz.",
      "Online alışverişin avantajlarından yararlanın: fiyat karşılaştırma, ürün detayları, kullanıcı yorumları ve para puan kazanımı. Her siparişte %5 para puan kazanın, bir sonraki siparişinizde kullanın.",
    ],
    features: [
      "900+ ürün çeşidi online",
      "7/24 sipariş verebilme",
      "Fiyat karşılaştırma kolaylığı",
      "Para puan kazanımı",
      "Aynı gün teslimat",
      "Kapıda ödeme seçenekleri",
      "Favorilere ekleme ve hatırlatma",
    ],
    faq: [
      { q: "Online pet shop'tan nasıl sipariş verilir?", a: "jetgo.shop adresine girin, ürünlerinizi sepete ekleyin ve WhatsApp üzerinden siparişinizi tamamlayın." },
      { q: "Online sipariş güvenli mi?", a: "Evet, ödeme kapıda yapılır. Nakit, POS veya QR kod ile güvenle ödeme yapabilirsiniz." },
      { q: "Online siparişte indirim var mı?", a: "Evet, nakit ödemede ekstra avantajlı fiyatlar sunuyoruz. Ayrıca her siparişte %5 para puan kazanırsınız." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
      { text: "Pet Aksesuar", href: "/pet-aksesuar" },
    ],
  },
  {
    slug: "acil-kedi-mamasi-samsun",
    type: "keyword",
    title: "Acil Kedi Maması Samsun",
    metaTitle: "Acil Kedi Maması Samsun - Hızlı Teslimat | JETGO Pet Shop",
    metaDescription: "Kedi maması bitti mi? Samsun'da acil kedi maması teslimatı. Royal Canin, Hill's, N&D aynı gün kapınıza. Hızlı sipariş, hızlı teslimat. JETGO.",
    keywords: "acil kedi maması, kedi maması acil teslimat, kedi maması bitti, acil mama samsun, hızlı kedi maması teslimat",
    h1: "Acil Kedi Maması Teslimatı - Samsun",
    intro: [
      "Kedi maması bitti ve acil ihtiyacınız mı var? JETGO ile Samsun'da aynı gün kedi maması teslimatı yapıyoruz. Royal Canin, Hill's, N&D, Pro Plan ve Reflex kedi mamalarını hızla kapınıza getiriyoruz.",
      "Kedinizin açlığını bekletmeyin! jetgo.shop üzerinden veya WhatsApp ile anında sipariş verin. Atakum, İlkadım ve Canik'e hızlandırılmış teslimat seçeneğimiz mevcuttur.",
      "Yavru kedi maması, yetişkin kedi maması, kısırlaştırılmış kedi maması - hangi türü ararsanız arayın, stoklarımızda hazır. Acil siparişleriniz için öncelikli teslimat yapıyoruz.",
    ],
    faq: [
      { q: "Acil kedi maması ne kadar sürede gelir?", a: "Acil siparişler ortalama 1-2 saat içinde teslim edilir. Atakum sahil şeridine daha da hızlı ulaşıyoruz." },
      { q: "Gece kedi maması sipariş verebilir miyim?", a: "Sipariş 7/24 verilebilir. Gece verilen siparişler sabah ilk teslimat rotasında kapınıza ulaştırılır." },
      { q: "Acil sipariş ek ücret var mı?", a: "Acil siparişlerde standart teslimat ücreti uygulanır, ek ücret yoktur." },
    ],
    internalLinks: [
      { text: "Kedi Maması Markaları", href: "/kedi-mamasi" },
      { text: "En İyi Kedi Maması", href: "/kedi-mamasi-en-iyi-markalar" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
    ],
  },
  {
    slug: "kopek-mamasi-hizli-teslim-samsun",
    type: "keyword",
    title: "Köpek Maması Hızlı Teslim Samsun",
    metaTitle: "Köpek Maması Hızlı Teslim Samsun - Aynı Gün Kapıda | JETGO",
    metaDescription: "Samsun'da köpek maması hızlı teslimat. 15 kg çuvalları taşımayın, biz getirelim. Royal Canin, Hill's, N&D, Pro Plan. Aynı gün kapıda ödeme. JETGO.",
    keywords: "köpek maması hızlı teslimat, köpek maması teslim samsun, büyük paket köpek maması teslimat, köpek maması kapıya teslim",
    h1: "Köpek Maması Hızlı Teslim - Samsun",
    intro: [
      "15 kiloluk köpek maması çuvallarını taşımak zor! JETGO ile Samsun'da köpek maması siparişinizi kapınıza teslim ediyoruz. Royal Canin, Hill's, N&D, Pro Plan, Reflex ve Pro Performance markalarını stokta tutuyoruz.",
      "Büyük ırk köpek sahipleri için ağır paketlerin kapıya teslimi büyük kolaylık. Yavru köpek mamasından yetişkin köpek mamasına, hassas sindirimden kilo kontrolüne her ihtiyaca uygun mama mevcut.",
      "Nakit ödemede ekstra avantajlı fiyatlar sunuyoruz. Her siparişte %5 para puan kazanın.",
    ],
    faq: [
      { q: "15 kg köpek maması teslimat yapıyor musunuz?", a: "Evet, ağır paketler dahil tüm ürünlerimizi kapınıza teslim ediyoruz. Taşıma derdi yok!" },
      { q: "Köpek maması aynı gün gelir mi?", a: "Evet, saat 17:00'ye kadar verilen siparişler aynı gün teslim edilir." },
      { q: "Büyük paketlerde indirim var mı?", a: "Büyük paketler zaten kg başı daha ekonomiktir. Ayrıca nakit ödemede ekstra avantaj ve %5 para puan kazanırsınız." },
    ],
    internalLinks: [
      { text: "Köpek Maması Fiyatları", href: "/kopek-mamasi-fiyatlari" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Atakum Pet Shop", href: "/atakum-petshop" },
    ],
  },
  {
    slug: "petshop-delivery-samsun",
    type: "keyword",
    title: "Pet Shop Delivery Samsun",
    metaTitle: "Pet Shop Delivery Samsun - Getir Model Evcil Hayvan Teslimatı | JETGO",
    metaDescription: "Samsun pet shop delivery hizmeti. Getir modeli ile evcil hayvan ürünleri kapınıza. Kedi köpek maması, kedi kumu aynı gün teslimat. JETGO.",
    keywords: "petshop delivery samsun, pet shop teslimat, pet shop kurye samsun, evcil hayvan teslimat, petshop getir samsun",
    h1: "Pet Shop Delivery Samsun - Getir Model Teslimat",
    intro: [
      "JETGO, Samsun'un ilk Getir modeli pet shop delivery hizmetidir. Evcil hayvan ürünlerinizi tıpkı yemek siparişi verir gibi online sipariş verin, aynı gün kapınıza teslim edelim.",
      "Geleneksel pet shop'lara gidip ağır çuvalları taşımak yerine, JETGO'nun delivery hizmeti ile evcil dostunuzun tüm ihtiyaçlarını telefonunuzdan karşılayın. Sipariş, teslimat ve ödeme sürecinin tamamı kapınızda.",
      "Samsun'un Atakum, İlkadım ve Canik ilçelerindeki tüm mahallelere düzenli teslimat rotalarımız mevcuttur. 900'den fazla ürün, premium markalar ve rekabetçi fiyatlarla hizmetinizdeyiz.",
    ],
    faq: [
      { q: "Pet shop delivery ne demek?", a: "Pet shop delivery, evcil hayvan ürünlerinin online sipariş ile kapınıza teslim edilmesi hizmetidir. JETGO bu hizmeti Samsun'da sunmaktadır." },
      { q: "Delivery süresi ne kadar?", a: "Ortalama 1-3 saat içinde teslimat yapıyoruz. Konumunuza ve sipariş yoğunluğuna göre değişebilir." },
      { q: "Delivery ücretsiz mi?", a: "Belirli tutar üzeri siparişlerde ücretsiz teslimat seçeneği mevcuttur. Mahalle bazlı detaylar sipariş sayfasında görüntülenir." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kapıya Teslim Pet Shop", href: "/kapiya-teslim-petshop-samsun" },
      { text: "En Yakın Pet Shop", href: "/en-yakin-petshop-samsun" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
    ],
  },
  {
    slug: "mama-siparis-samsun",
    type: "keyword",
    title: "Mama Sipariş Samsun",
    metaTitle: "Mama Sipariş Samsun - Kedi Köpek Maması Online Sipariş | JETGO",
    metaDescription: "Samsun'da kedi ve köpek maması online sipariş. Royal Canin, Hill's, N&D, Pro Plan en uygun fiyatlarla. Aynı gün kapıya teslim, kapıda ödeme. JETGO.",
    keywords: "mama sipariş samsun, kedi maması sipariş, köpek maması sipariş, online mama sipariş, kapıya mama sipariş",
    h1: "Samsun Mama Sipariş - Kedi & Köpek Maması",
    intro: [
      "Samsun'da kedi ve köpek maması sipariş etmek artık çok kolay! JETGO ile Royal Canin, Hill's, N&D, Pro Plan, Reflex ve daha birçok premium marka mamayı online sipariş verin, aynı gün kapınıza teslim edelim.",
      "Yavru mama, yetişkin mama, kısırlaştırılmış mama, diyet mama, hassas sindirim maması - hangi türü ararsanız arayın, geniş ürün yelpazemizde bulabilirsiniz. Kuru mama, yaş mama ve ödül maması seçenekleri mevcut.",
      "Nakit ödemede avantajlı fiyat ve her siparişte %5 para puan kazanımı. Mama siparişinizi JETGO ile verin, hem tasarruf edin hem de kolaylıktan yararlanın.",
    ],
    faq: [
      { q: "Mama sipariş nasıl verilir?", a: "jetgo.shop adresinden ürünlerinizi sepete ekleyin, ardından WhatsApp ile siparişinizi tamamlayın." },
      { q: "Mama siparişi aynı gün gelir mi?", a: "Evet, saat 17:00'ye kadar verilen mama siparişleri aynı gün teslim edilir." },
      { q: "En ucuz mama siparişi nereden verilir?", a: "JETGO'da nakit ödeme fiyatları piyasanın en uygun fiyatlarıdır. Ayrıca %5 para puan ile ekstra tasarruf sağlarsınız." },
    ],
    internalLinks: [
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Kedi Maması Markaları", href: "/kedi-mamasi-en-iyi-markalar" },
      { text: "Köpek Maması Fiyatları", href: "/kopek-mamasi-fiyatlari" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
    ],
  },
  {
    slug: "kedi-kumu-kapiya-teslim-samsun",
    type: "keyword",
    title: "Kedi Kumu Kapıya Teslim Samsun",
    metaTitle: "Kedi Kumu Kapıya Teslim Samsun - Ağır Kumu Biz Taşıyalım | JETGO",
    metaDescription: "Samsun'da kedi kumu kapıya teslim. Ağır bentonit kumu taşımayın, biz getirelim. Van Cat, Biokat's, Sanicat. Aynı gün teslimat. JETGO Pet Shop.",
    keywords: "kedi kumu kapıya teslim, kedi kumu teslimat samsun, kedi kumu sipariş, ağır kedi kumu teslimat, bentonit kum kapıya teslim",
    h1: "Kedi Kumu Kapıya Teslim - Samsun",
    intro: [
      "10-20 kiloluk kedi kumu çuvallarını apartmanınıza taşımak çok zor! JETGO ile Samsun'da kedi kumunuzu kapınıza teslim ediyoruz. Ağır kaldırma derdi artık yok.",
      "Van Cat, Biokat's, Sanicat ve daha birçok marka bentonit, silika ve doğal kedi kumlarını geniş yelpazemizde bulabilirsiniz. Topaklanan, aktif karbonlu, aromalı ve ince taneli seçenekler mevcut.",
      "Düzenli kedi kumu siparişi için hatırlatma özelliğimizi kullanın. Kumunuz bitmeden önce otomatik bildirim alın, zamanında sipariş verin.",
    ],
    faq: [
      { q: "Ağır kedi kumunu kapıya teslim ediyor musunuz?", a: "Evet! 10-20 kg kedi kumlarını dahil tüm ürünleri kapınıza kadar teslim ediyoruz. Apartman katınıza kadar çıkarıyoruz." },
      { q: "En iyi kedi kumu hangisi?", a: "Topaklanan bentonit kumlar en çok tercih edilen türdür. Aktif karbonlu Van Cat ve Biokat's Bianco Fresh en popüler seçeneklerdir." },
      { q: "Kedi kumu kapıya teslim ücreti ne kadar?", a: "Teslimat ücreti mahallenize göre değişir. Belirli tutar üzeri siparişlerde ücretsiz kargo mevcuttur." },
    ],
    internalLinks: [
      { text: "Kedi Kumu Karşılaştırma", href: "/kedi-kumu-en-iyi" },
      { text: "Kedi Kumu Ürünleri", href: "/kedi-kumu" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
    ],
  },
  {
    slug: "samsun-evcil-hayvan-magazasi",
    type: "keyword",
    title: "Samsun Evcil Hayvan Mağazası",
    metaTitle: "Samsun Evcil Hayvan Mağazası - Online Sipariş Kapıya Teslim | JETGO",
    metaDescription: "Samsun evcil hayvan mağazası online. Kedi, köpek, kuş, kemirgen ürünleri. 900+ ürün, premium markalar. Aynı gün kapıya teslim. JETGO Pet Shop.",
    keywords: "samsun evcil hayvan mağazası, evcil hayvan ürünleri samsun, pet mağazası samsun, hayvan mağazası samsun",
    h1: "Samsun Evcil Hayvan Mağazası - Online & Kapıya Teslim",
    intro: [
      "Samsun'un en kapsamlı online evcil hayvan mağazası JETGO ile tanışın. Kedi, köpek, kuş ve kemirgen sahipleri için 900'den fazla ürün çeşidi sunuyoruz.",
      "Geleneksel pet mağazalarından farklı olarak, JETGO'da tüm alışverişinizi online yapabilir ve aynı gün kapınıza teslim alabilirsiniz. Premium markalar, uygun fiyatlar ve kapıda ödeme kolaylığı.",
      "Mama, kum, aksesuar, bakım ürünleri, vitamin, ödül maması - evcil dostunuz için ne ararsanız JETGO'da bulun. Her siparişte %5 para puan kazanın.",
    ],
    faq: [
      { q: "Samsun'da evcil hayvan mağazası var mı?", a: "Evet, JETGO Samsun'un online evcil hayvan mağazasıdır. 900+ ürünü kapınıza teslim ediyoruz." },
      { q: "Kuş yemi ve kemirgen ürünleri de var mı?", a: "Evet, kedi ve köpek ürünlerinin yanı sıra kuş yemi, kuş kafesi, kemirgen yemi ve aksesuarları da satıyoruz." },
      { q: "Evcil hayvan mağazası online alışveriş güvenli mi?", a: "Evet, ödeme kapıda yapılır. Nakit, POS veya QR kod ile güvenle ödeyebilirsiniz." },
    ],
    internalLinks: [
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Köpek Maması", href: "/kopek-mamasi" },
      { text: "Pet Aksesuar", href: "/pet-aksesuar" },
      { text: "Online Pet Shop", href: "/online-petshop-samsun" },
    ],
  },
  {
    slug: "samsun-kedi-mamasi-fiyatlari",
    type: "keyword",
    title: "Samsun Kedi Maması Fiyatları",
    metaTitle: "Samsun Kedi Maması Fiyatları 2026 - En Uygun Fiyat | JETGO Pet Shop",
    metaDescription: "Samsun'da kedi maması fiyatları 2026. Royal Canin, Hill's, N&D, Pro Plan kedi maması güncel fiyatlar. Nakit ödemede ekstra indirim. JETGO.",
    keywords: "samsun kedi maması fiyat, kedi maması fiyatları samsun, ucuz kedi maması samsun, kedi maması indirim samsun",
    h1: "Samsun Kedi Maması Fiyatları 2026",
    intro: [
      "Samsun'da en uygun kedi maması fiyatlarını JETGO'da bulun. Nakit ödemede ekstra avantajlı fiyatlarımızla piyasanın en rekabetçi fiyatlarını sunuyoruz.",
      "Royal Canin, Hill's Science Plan, N&D Farmina, Pro Plan, Reflex Plus ve Profine gibi premium markaların güncel fiyatlarını karşılaştırın. 1,5 kg'dan 15 kg'a kadar tüm paket seçenekleri mevcut.",
      "Her siparişte %5 para puan kazanarak bir sonraki alışverişinizde ekstra tasarruf sağlayın. Büyük paketlerde kg başı daha ekonomik fiyatlar sunuyoruz.",
    ],
    features: [
      "Royal Canin 2 kg: 650 - 850 TL",
      "Royal Canin 10 kg: 3.500 - 4.500 TL",
      "Hill's 3 kg: 900 - 1.400 TL",
      "N&D 1,5 kg: 700 - 1.100 TL",
      "Pro Plan 3 kg: 750 - 1.050 TL",
      "Reflex Plus 8 kg: 1.200 - 1.600 TL",
      "Profine 2 kg: 550 - 750 TL",
    ],
    faq: [
      { q: "Samsun'da en ucuz kedi maması nerede?", a: "JETGO Pet Shop, nakit ödeme fiyatlarıyla Samsun'da en uygun kedi maması fiyatlarını sunmaktadır." },
      { q: "Kedi maması indirim var mı?", a: "Nakit ödemede ekstra avantajlı fiyat sunuyoruz. Ayrıca her siparişte %5 para puan kazanırsınız." },
      { q: "Kedi maması ödeme yöntemleri neler?", a: "Kapıda nakit (%5 indirim), POS ile kredi kartı, QR ödeme ve banka havalesi seçenekleri mevcuttur." },
    ],
    internalLinks: [
      { text: "Kedi Maması Markaları", href: "/kedi-mamasi-en-iyi-markalar" },
      { text: "Kedi Maması", href: "/kedi-mamasi" },
      { text: "Kedi Kumu", href: "/kedi-kumu" },
      { text: "Samsun Pet Shop", href: "/samsun-petshop" },
    ],
  },
];

SEO_PAGES.push(...MAHALLE_PAGES, ...KEYWORD_PAGES);
