"use client";
import {useState} from "react";import {Globe2,Menu,Heart,MessageCircle,MapPin,BookOpen,Users,Camera,Sparkles,ChevronRight} from "lucide-react";import {dictionaries,languages,Lang} from "@/lib/i18n";
const Pic=({src,alt,c=""}:{src:string,alt:string,c?:string})=><img src={src} alt={alt} className={c}/>;
const Btn=({children,outline=false}:{children:React.ReactNode,outline?:boolean})=><button className={outline?"btn outline":"btn"}>{children}</button>;
export default function HomePage(){const[lang,setLang]=useState<Lang>("tr");const t=dictionaries[lang];const types=[["/images/toy-poodle.jpg",t.types[0]],["/images/miniature-poodle.jpg",t.types[1]],["/images/standard-poodle.jpg",t.types[2]]];
return <main>
<header className="section header" id="YP-01"><div className="brand">🐾 <b>YourPoodle</b></div><nav>{t.nav.map(x=><a key={x}>{x}</a>)}</nav><div className="actions"><label><Globe2/><select value={lang} onChange={e=>setLang(e.target.value as Lang)}>{languages.map(x=><option key={x}>{x.toUpperCase()}</option>)}</select></label><button className="login">{t.login}</button><Btn>{t.join}</Btn><Menu className="menu"/></div></header>
<section className="section hero" id="YP-02"><div className="heroCopy"><span className="eyebrow">🐩 ONE GLOBAL POODLE FAMILY</span><h1>{t.heroTitle}</h1><p>{t.heroSub}</p><div className="buttons"><Btn>{t.create}<ChevronRight/></Btn><Btn outline>{t.explore}</Btn></div></div><div className="heroPic"><Pic src="/images/hero-poodles.jpg" alt="Poodles" c="cover"/><div className="float">🌍 <span><b>Global Poodle Community</b><small>Toy • Miniature • Standard</small></span></div></div></section>
<section className="section benefits" id="YP-03">{[Camera,Users,Sparkles,Heart].map((I,i)=><div key={t.benefits[i]}><I/><b>{t.benefits[i]}</b></div>)}</section>
<section className="section block" id="YP-04"><Title eye="POODLE FAMILY" title={t.typesTitle} sub={t.typesSub}/><div className="cards">{types.map(([src,n])=><article className="type" key={n}><Pic src={src} alt={n} c="cover"/><div><h3>{n}</h3><span>Explore →</span></div></article>)}</div></section>
<section className="world" id="YP-05"><div className="section block"><Title eye="🌍 ONE GLOBAL POODLE FAMILY" title={t.worldTitle} sub={t.worldSub}/><div className="map"><strong>WORLD</strong>{["🇹🇷 İstanbul","🇺🇸 New York","🇬🇧 London","🇫🇷 Paris","🇩🇪 Berlin","🇯🇵 Tokyo","🇦🇺 Sydney","🇨🇦 Toronto"].map((x,i)=><span className={"p p"+i} key={x}>{x}</span>)}</div></div></section>
<section className="section block" id="YP-06"><Title eye="COMMUNITY" title={t.communityTitle} sub={t.communitySub}/><div className="feed">{[["Milo","İstanbul","community-1.jpg"],["Luna","Paris","community-2.jpg"],["Teddy","London","community-3.jpg"]].map(([n,p,img])=><article className="post" key={n}><header><i>{n[0]}</i><span><b>{n}</b><small><MapPin/>{p}</small></span></header><Pic src={"/images/"+img} alt={n} c="postpic"/><p>Bugünün en güzel anı 🐩💚</p><footer><span><Heart/> Beğen</span><span><MessageCircle/> Yorum</span></footer></article>)}</div></section>
<section className="section split" id="YP-07"><div><span className="eyebrow">POODLE FRIENDS</span><h2>{t.friendsTitle}</h2><p>{t.friendsSub}</p><Btn>{t.explore}</Btn></div><Pic src="/images/poodle-friends.jpg" alt="Friends" c="feature"/></section>
<section className="section block" id="YP-08"><Title eye="POODLE GUIDE" title={t.guideTitle} sub={t.guideSub}/><div className="guides">{["✂️ Bakım","🎓 Eğitim","🥣 Beslenme","💚 Poodle Yaşamı"].map(x=><div key={x}>{x}</div>)}</div></section>
<section className="section join" id="YP-09"><div><span className="eyebrow light">YOURPOODLE</span><h2>{t.ctaTitle}</h2><p>{t.ctaSub}</p><Btn>{t.create}<ChevronRight/></Btn></div><b className="dogs">🐩🐩🐩</b></section>
<footer className="siteFooter" id="YP-11"><div className="section"><div className="brand">🐾 <b>YourPoodle</b></div><p>{t.footer}</p><small>© 2026 YourPoodle • One Global Poodle Family</small></div></footer>
</main>}
function Title({eye,title,sub}:{eye:string,title:string,sub:string}){return <div className="title"><span className="eyebrow">{eye}</span><h2>{title}</h2><p>{sub}</p></div>}