uploads = []

[[generated]]
id = "l3NJwlQ2CqaRNN7bUHvC8"
uri = "file://attached_assets/cat-fish.png"
type = "image"
title = "betta fish category image"

[[outputs]]
id = "9y2QoewR6z_sxq3OzRlmR"
uri = "file://jetgo_urunler.xlsx"
type = "table"
title = "JETGO Ürünler (Excel)"

[[outputs]]
id = "tCTBZ3-hFo7hNItuoR43i"
uri = "file://jetgo_urunler.yml"
type = "unspecified"
title = "JETGO Ürünler (Yandex Business YML)"
