// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-2026/Modern.tsx": () => import("../components/mockups/homepage-2026/Modern.tsx"),
  "./components/mockups/jetgo-landing/Landing.tsx": () => import("../components/mockups/jetgo-landing/Landing.tsx")
};
